### PR TITLE
Treat IEnumerable simillar to IList

### PR DESCRIPTION
**Pull request by mcanti**
If the source is IEnumerable treat it as an IList by the ListFormatter.

### CODE REVIEW

**Comment by scottrippey** [comment]
Well, let's discuss this change...
I actually didn't want SmartFormat to implicitly "execute" anything when running the template.
Converting an IEnumerable to an IList will enumerate it and gather the results, which will likely execute code, could make database calls, and could have side-effects.  

So that's why I intentionally required an IList -- I want the "gather" step to happen outside of SmartFormat -- so that developers are aware that it's happening, and it ought to be easier to debug errors, etc.

For your use-case, would it be difficult to do something like this?
```
Smart.Format("{0:list:{}|,}", items.ToList());
```

**Comment by mcanti** [comment]
Hi Scott,

I understand your point.
SmartFormat resolves properties or parameter-less methods. Thus it could,
in theory, execute code, make database calls, etc.

My problem is that I receive a business object from an underlying layer
which contains data from Linq queries, those the type for instance
System.Linq.Enumerable+WhereArrayIterator`1.

If you decide not to have this case covered, then I think developers still
have the option to develop a EnumerableSource and register it to the
default formatter, right?

On Thu, May 12, 2016 at 6:28 PM, Scott Rippey <notifications@github.com>
wrote:

> Well, let's discuss this change...
> I actually didn't want SmartFormat to implicitly "execute" anything when
> running the template.
> Converting an IEnumerable to an IList will enumerate it and gather the
> results, which will likely execute code, could make database calls, and
> could have side-effects.
>
> So that's why I intentionally required an IList -- I want the "gather"
> step to happen outside of SmartFormat -- so that developers are aware that
> it's happening, and it ought to be easier to debug errors, etc.
>
> For your use-case, would it be difficult to do something like this?
>
> Smart.Format("{0:list:{}|,}", items.ToList());
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/scottrippey/SmartFormat.NET/pull/76#issuecomment-218793511>
>



-- 
----
Best regards / Mit freundlichen Grüssen
Cantemir Mihu

**Comment by scottrippey** [comment]
Well, you've got a good use-case.  You've got a business object that you're passing in, and you want to use it as-is, instead of doing something like `new { Items = obj.Items.ToList() }`.

What I'm trying to protect against is double enumeration.  If an object is IEnumerable but NOT ICollection, then the implication is that the data hasn't been collected yet, so getting the Count could be an expensive operation (ie. processing a long list or making database calls).
So if your template uses `items` twice, like `There {items:plural:is 1 item|are {} items}: {items:list:{Name}|, }`, then you could be double-enumerating the list without realizing it.

Having said that, I'm realizing that it's very unlikely that we would ever use the `list` formatter more than once in a template.  So, perhaps if we're enforcing `ICollection` for the `plural` formatter, then we can allow `IEnumerable` for the `list` formatter.  Does that make sense?

**Comment by mcanti** [comment]
In order to avoid double enumeration, the IEnumerable source formatter
could make use of a cache where it would store already converted sources.
But as you said, it's very unlikely.

Allowing IEnumerable for the list formatter makes sense, imho.

On Fri, May 13, 2016 at 7:34 PM, Scott Rippey <notifications@github.com>
wrote:

> Well, you've got a good use-case. You've got a business object that you're
> passing in, and you want to use it as-is, instead of doing something like new
> { Items = obj.Items.ToList() }.
>
> What I'm trying to protect against is double enumeration. If an object is
> IEnumerable but NOT ICollection, then the implication is that the data
> hasn't been collected yet, so getting the Count could be an expensive
> operation (ie. processing a long list or making database calls).
> So if your template uses items twice, like There {items:plural:is 1
> item|are {} items}: {items:list:{Name}|, }, then you could be
> double-enumerating the list without realizing it.
>
> Having said that, I'm realizing that it's very unlikely that we would ever
> use the list formatter more than once in a template. So, perhaps if we're
> enforcing ICollection for the plural formatter, then we can allow
> IEnumerable for the list formatter. Does that make sense?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/scottrippey/SmartFormat.NET/pull/76#issuecomment-219094274>
>



-- 
----
Best regards / Mit freundlichen Grüssen
Cantemir Mihu

**Comment by SeriousM** [comment]
Double enumeration is one problem and you shouldn't cache the output
because the content could be houge.
The other problem is that enumerate an enumerable may empty it and it's
impossible to read it again (db sets for example). Therefore you would
create an side effect which isn't obvious to everyone.
Passing only IEnumerable around is a bad pattern anyway because you never
know when the content is materialized (read and stored in the memory) and
one have to call ToList or ToArray all the time to ensure that double
enumeration is avoided.
Am 15.05.2016 06:58 schrieb "mcanti" <notifications@github.com>:

In order to avoid double enumeration, the IEnumerable source formatter
could make use of a cache where it would store already converted sources.
But as you said, it's very unlikely.

Allowing IEnumerable for the list formatter makes sense, imho.

On Fri, May 13, 2016 at 7:34 PM, Scott Rippey <notifications@github.com>
wrote:

> Well, you've got a good use-case. You've got a business object that you're
> passing in, and you want to use it as-is, instead of doing something like
new
> { Items = obj.Items.ToList() }.
>
> What I'm trying to protect against is double enumeration. If an object is
> IEnumerable but NOT ICollection, then the implication is that the data
> hasn't been collected yet, so getting the Count could be an expensive
> operation (ie. processing a long list or making database calls).
> So if your template uses items twice, like There {items:plural:is 1
> item|are {} items}: {items:list:{Name}|, }, then you could be
> double-enumerating the list without realizing it.
>
> Having said that, I'm realizing that it's very unlikely that we would ever
> use the list formatter more than once in a template. So, perhaps if we're
> enforcing ICollection for the plural formatter, then we can allow
> IEnumerable for the list formatter. Does that make sense?
>
> —
> You are receiving this because you authored the thread.

> Reply to this email directly or view it on GitHub
> <
https://github.com/scottrippey/SmartFormat.NET/pull/76#issuecomment-219094274
>

>



-- 
----
Best regards / Mit freundlichen Grüssen
Cantemir Mihu

—

You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/scottrippey/SmartFormat.NET/pull/76#issuecomment-219266419>

**Comment by mcanti** [comment]
Ok, thanks for your input. You can delete this pull request.

I have another question: how would you go about creating a list formatter, which allows numbering of each item?

`Format("{Items|, |, and }", {"First item", "Second item", "Third item"}) = 1. First item, 2. Second item, and 3. Third item`

Would I need to create a similar formatter to ListFormatter?

**Comment by scottrippey** [comment]
I do think you can do this, using the `{Index}` variable; or perhaps more appropriate, I think you can do `{Index+1}`

**Comment by mcanti** [comment]
Hi Scott,

{Index+1} doesn't seem to work. How can I force the enumeration to start at 1?
And what about avoiding the numbering if List contains only one element?

**Comment by scottrippey** [comment]
Sorry, I was wrong thinking that `{Index+1}` would work; this kind of expression-parsing isn't supported, I forgot. I guess there's no way to enumerate from 1.

**Pull request closed without merging**
